name: dbt CI

on:
  push:
    branches:
      - main

jobs:
  dbt-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: |
          pip install dbt-core
          pip install dbt-snowflake

      - name: Install Packages
        run: dbt deps

      - name: Run Tests
        run: dbt test

      - name: Run Models
        run: dbt run